### ISSUE TITLE
STM32F103 - Arduino IDE Support

### ISSUE THREAD

**Issue by drmarian** [Marzogh/SPIMemory#148] opened 2018-08-08 11:20 UTC
![GitHub issue state](https://img.shields.io/github/issues/detail/s/Marzogh/SPIFlash/148.svg) ![GitHub issue title](https://img.shields.io/github/issues/detail/title/Marzogh/SPIFlash/148.svg)
![GitHub issue author](https://img.shields.io/github/issues/detail/u/Marzogh/SPIFlash/148.svg) ![GitHub issue label](https://img.shields.io/github/issues/detail/label/Marzogh/SPIFlash/148.svg) ![GitHub issue comments](https://img.shields.io/github/issues/detail/comments/Marzogh/SPIFlash/148.svg)
![GitHub issue age](https://img.shields.io/github/issues/detail/age/Marzogh/SPIFlash/148.svg) ![GitHub issue last update](https://img.shields.io/github/issues/detail/last-update/Marzogh/SPIFlash/148.svg)
###### ---------------------------- **DO NOT DELETE OR EDIT** anything above this line ----------------------------

# Issue details

**I'm submitting a ...**
  - [x] bug report

Do the checklist before filing an issue:

- [X] Is this a bug that you cannot fix? Post the bug report as an issue here with a title that cleary says "Bug Report".

When opening an issue please include the following details:
-------------------------------------------------------------

- [x] Do you want to request a *feature* or report a *bug*? - bug
- [x] Which library version are you using? - latest
- [x] Which Arduino IDE version are you compiling the library on? - latest
- [x] Which OS are you compiling your code on? [Linux / Mac / Windows] - Win10 x64
- [x] Which microcontroller platform are you using? - BluePillSTM32F103
- [x] Which Flash memory module are you using? - Winbond  W25Q16BV
- [x] What is the current behavior? - hangs
- [x] What is the expected behavior? - works

--------------------------
###### Bug reports only
- If this is a bug report -

- [x] Make sure you have run FlashDiagnostics.ino with ``` #define RUNDIAGNOSTICS ``` uncommented in SPIFlash.h. **List any error codes** that pop up in your Serial output when you run FlashDiagnostics.ino.here:
      Error codes
      ------------
        - no codes. mcu hangs.... i have to add delay(100) before every flash function to get it work...

-----------------------------

**Comment by Marzogh** [comment] 2018-08-09 05:04
Duplicate of #116

**Comment by Marzogh** [comment] 2018-08-10 14:48
Ref: #116

**Closed by Marzogh** 2018-08-10 14:48 UTC
Labels: duplicate, possible bug

**Comment by orkunkilinc** [comment] 2019-08-27 11:45
Can confirm this problem, on rogerclarke's STM32 core normally working flash(works an AVR) chip hangs the STM32 right after getID() with FlashDiagnostics sketch. Turning on RUNDIAGNOSTICS instantly hangs the MCU.
